<?php

namespace Tests;

use PHPUnit\Framework\TestCase;

require_once(__DIR__ . '/../vendor/autoload.php');


class FileEditorTest extends TestCase
{
    public function testNoInputFile()
    {
    }

    public function testHasInputFile()
    {
        $fileEditor = new FileEditor($this->testPath);
        $this->assertIsObject($fileEditor);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
