<?php

    use PHPUnit\Framework\TestCase;

    require_once(__DIR__ . '/../vendor/autoload.php');


    class FileEditorTest extends TestCase
    {

        protected function setUp(): void
        {
            parent::setUp(); // TODO: Change the autogenerated stub
        }

        protected function tearDown(): void
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
        }

        public function test_noInputFile()
        {

        }

        public function test_hasInputFile()
        {
            $fileEditor = new FileEditor($this->testPath);
            $this->assertIsObject($fileEditor);
        }

    }
